package de.pathologie_hh_west.model;

/**
 * Created by VaniR on 10.07.2017.
 */
public enum BefundTyp {
    HAUPTBEFUND, KONSILIARBERICHT, KORREKTURBEFUND1, KORREKTURBEFUND2, KORREKTURBEFUND3, KORREKTURBEFUND4, NACHBERICHT1, NACHBERICHT2, UNBEKANNT;
}
